homework_5
alexgo92/-Go_first_level_homework pull request #5
Opened 2021-12-01 08:14 UTC by alexgo92

Задания: 
1. Напишите приложение, рекурсивно вычисляющее заданное из стандартного ввода число Фибоначчи.
2. Оптимизируйте приложение за счёт сохранения предыдущих результатов в мапе.

2021-12-01 15:59 UTC, v-lozhkin commented on homework_5/main.go
> +				valuesFib[num] = numberFibonacci(num)
Это сейчас оптимизация в виде кеша для повторных просчетов чисел. 
В задании имеется ввиду оптимизация самого алгоритма. То есть мапу нужно использовать для оптимизации в самой рекуррентной функции (подсказка - обратите внимание, что для просчета очередного числа в рекурсии используются числа, которые уже находились при подсчете предыдущего, почему бы их не сохранить?)

2021-12-02 13:56 UTC, alexgo92 commented on homework_5/main.go
> +				valuesFib[num] = numberFibonacci(num)
Надеюсь, сейчас правильно понял)

2021-12-02 13:57 UTC, alexgo92 commented on homework_5/main.go
> +				valuesFib[num] = numberFibonacci(num)
Только забыл осмысленно мапу назвать...

2021-12-02 19:29 UTC, v-lozhkin requested changes

2021-12-02 19:29 UTC, v-lozhkin commented on homework_5/main.go
> +		FibMap[num+1] = FibMap[num] + FibMap[num-1]
Уже ближе к правде, но зачем тут считать наперед? (FibMap[num+1]) оно нам может и не понадобится

2021-12-03 07:19 UTC, alexgo92 commented on homework_5/main.go
> +		FibMap[num+1] = FibMap[num] + FibMap[num-1]
Исправил

2021-12-03 11:42 UTC, v-lozhkin approved these changes

2021-12-03 11:42 UTC, v-lozhkin commented on homework_5/main.go
> +		fmt.Println("v if")
Лишний дебаг, но все хорошо, принято

2021-12-03 11:53 UTC, merged